wandb_version: 1

Architecture:
  desc: null
  value: GAN
_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1671280383.178175
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.9.13
      5: 0.13.4
      8:
      - 3
      - 5
augment:
  desc: null
  value: None
trainer:
  desc: null
  value: WGANTrainer
